######################################################################
# Automatically generated by qmake (2.01a) So. Jan 20 14:17:52 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += config.hpp
SOURCES += config.cpp main.cpp
